### ISSUE TITLE
Cannot use cairo with graph-tool

### ISSUE THREAD

**Issue by sulantha2006** [ptorrestr/conda-recipes#1]
Hi I am trying to use graph-tool with anaconda and the tools itself(analysis) is working. But when I try to use graph_draw I get a cairo error (icu version 56 error). 
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

`Package plan for installation in environment /home/sulantha/anaconda3:

The following packages will be UPDATED:

```
cairo: 1.12.18-8 conda-forge --> 1.14.6-1 ptorrestr
```

The following packages will be DOWNGRADED due to dependency conflicts:

```
icu:   56.1-0    ostrokach   --> 54.1-0   ostrokach
```

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################| 100%
sulantha@sacks:~$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import cairo
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/sulantha/anaconda3/lib/python3.5/site-packages/cairo/**init**.py", line 18, in <module>
> > >     from ._cairo import *
> > > ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory`

But when I try to upgrade cairo to version 56, I get libicudata.so.54 error indicating icu version 54 missing. 
`Traceback (most recent call last):
  File "/home/sulantha/PycharmProjects/NetworkAnalysis/Analysis/getGraphAttributes.py", line 4, in <module>
    from graph_tool import topology
  File "/home/sulantha/anaconda3/lib/python3.5/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/sulantha/anaconda3/lib/python3.5/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: libicudata.so.54: cannot open shared object file: No such file or directory`

Can you help?

**Comment by ptorrestr** [comment]
Hi @sulantha2006,

Since I didn't include cairo in the original recipe, several gtk libraries weren't included in the final package. Besides, the recipe was built using icu54, creating this library conflict. I'm going to include now cairo and all the additional requirements for gtk.  Hope it will work now for you.
